CREATE TABLE IF NOT EXISTS NOTES
(
    ID BIGSERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    BODY VARCHAR(1000) NOT NULL,
    CREATION_DATE TIMESTAMP,
    CONSTRAINT FK_NOTES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON
    DELETE CASCADE ON UPDATE NO ACTION
);

CREATE SEQUENCE NOTE_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1000
    CACHE 10;