CREATE TABLE IF NOT EXISTS NOTES_HISTORY
(
    ID BIGSERIAL PRIMARY KEY,
    NOTE_ID BIGINT NOT NULL,
    TITLE VARCHAR(255),
    BODY VARCHAR(1000),
    MODIFICATION_DATE TIMESTAMP,
    ACTION_TYPE VARCHAR(10) CHECK (ACTION_TYPE IN ('CREATE', 'UPDATE','DELETE')),
    CONSTRAINT FK_NOTES_HISTORY_NOTES FOREIGN KEY (NOTE_ID) REFERENCES NOTES (ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE SEQUENCE NOTE_HISTORY_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1000
    CACHE 10;