CREATE TABLE IF NOT EXISTS NOTE_IMAGES
(
    IMAGE_NAME VARCHAR(255) PRIMARY KEY,
    NOTE_ID BIGINT NOT NULL,
    CONSTRAINT FK_NOTE_IMAGES_NOTES FOREIGN KEY (NOTE_ID) REFERENCES
    NOTES (ID) ON DELETE CASCADE ON UPDATE NO ACTION
);